#!/bin/bash

#################################################################
###                                                           ###
###              EJBCA Backup Script for MariaDB              ###
###                                                           ###
#################################################################

# This script creates a backup of your MariaDB databases using
# the mariabackup utility. See https://mariadb.com/kb/en/library/mariabackup/
# All backups are encrypted with the GPG utility.
#
# If this script is executed by any other user than root, make
# sure this user is in the mysql group. You should also prepare
# a MariaDB user used for backing up data only. This user can be
# created as follows:
# mysql> CREATE USER 'backup'@'localhost' IDENTIFIED BY 'foo123';
# mysql> GRANT RELOAD, LOCK TABLES, PROCESS, REPLICATION CLIENT ON *.* TO 'backup'@'localhost';
# mysql> FLUSH PRIVILEGES;

# Location of the MariaDB configuration file with the username
# and passphrase for the backup user. This file should have the
# following contents:
# [client]
# user=backup
# password=foo123
#
# [mysqld]
# datadir=/var/lib/mysql
MYSQL_CNF='/opt/jboss/backup/mysql_backup.cnf'

# Backup directory, will be created if it does not exist. Can be
# mapped to e.g. an NFS share.
BACKUP_DIR='/nfs'

# The passphrase used to protect the backup, clear this variable
# to make the script ask for the passphrase.
BACKUP_PWD="foo123"

################################################################

# This will create XtraBackup files directory in /var/lib/mysql instead of
# cluttering the user's current working directory.
cd /var/lib/mysql

if [ ! -f "$MYSQL_CNF" ]; then
  echo "The MySQL configuration file $MYSQL_CNF does not exist."
  exit 1
fi

# The user running this script must be in the wheel group, unless
# the script is running as root
if [ "$UID" -ne 0 ]; then
  exec sudo bash "$0" "$@"
fi

if [ "$(id -u)" != "0" ]; then
  echo "Root access denied."
  exit 1
fi

# The MariaDB database files are only readable by the mysql user
# by default, make sure everyone in the mysql group can read them
chmod -R g=u /var/lib/mysql

if [ -z "$BACKUP_PWD" ]; then
  read -s -p 'Backup password: ' PWD
  echo ""
  read -s -p 'Repeat backup password: ' PWD2
  echo ""
  if [ "$BACKUP_PWD" != "$BACKUP_PWD2"  ]; then
    echo "Passwords do not match."
    exit 1
  fi
fi

# Create the backup directory if it does not already exist
if [ ! -d "$BACKUP_DIR" ]; then
  mkdir -p "$BACKUP_DIR"
fi

DATE=$(date '+%Y%m%d%H%M%S')
HOSTNAME=$(hostname)
BACKUP_NAME="mb_ejbca_${HOSTNAME}_${DATE}"

# Create the backup in the backup directory e.g.
# /var/opt/backups/mb_ejbca_hostname_20180101133700.xb.gpg
echo 'Compressing and encrypting backup... (this may take some time)'
mariabackup --defaults-extra-file="$MYSQL_CNF" \
  --host=127.0.0.1 \
  --backup \
  --stream=xbstream | \
openssl enc -e -aes-256-cbc -md sha256 -pass "pass:$BACKUP_PWD" -out "${BACKUP_DIR}/${BACKUP_NAME}.xb.enc"
